server:
  port: 20000

spring:
  application:
    name: cms-eureka
  profiles:
    active: dev

eureka:
  server:
    enable-self-preservation: false # 禁用自我保护模式
  instance:
    hostname: localhost # eureka 服务端的实例名称
  client:
    registerWithEureka: false # 服务注册,false表示不将集资注册到Eureka服务中心
    fetchRegistry: false # 服务发现 false表示自己不从Eureka服务中获取注册信息
    serviceUrl: # Eureka客户端与Eureka服务端的交互地址,  集群版配置对方的地址  单机版配置自己(如果不配置默认端口是8761)
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/